Open a Pull request
Marcraphael12/Hello-MICROVERSE pull request #2
Opened 2021-08-09 11:31 UTC by Marcraphael12

Checking if the GitHub flow is good and if the linters are working propely

2021-08-09 11:43 UTC, carlos-ssh requested changes
Hi @Marcraphael12 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
Your project it's nice and covers requirements requested for your project.
Kindly work on the requested changes at the bottom 👇🏼


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Commit messages should be meaningful.
- Pull Request should have a descriptive title telling you what changes are inside.
- Pull Request should have a short summary describing introduced changes in more details.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-09 11:46 UTC, carlos-ssh commented on index.html
>  </html>
- There is a .gitignore file listing test.md file and `node_modules` directory (as it can be added by accident while setting up linters).
- README file should be descriptive with general information about your project.

2021-08-09 13:27 UTC, Marcraphael12 commented on index.html
>  </html>
sorry but we are not supposed to skip the 'nodes modules', and I don't really know how to!

2021-08-09 13:36 UTC, carlos-ssh requested changes
Hi @Marcraphael12 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-09 13:36 UTC, carlos-ssh commented on README.md
**Kindly work on this change:**
- README file should be descriptive.
(Provide a License, General information about your project, How to run your project locally and how to install).

2021-08-10 07:20 UTC, DanteAlonsoHT approved these changes
<h1>Status: Approve 🥇 ✔</h1>

Hi @Marcraphael12, 

Your project is complete!  There is nothing else to say because you have been working well with the minimum requirements for this project... It's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding, I know you did a good effort to complete it!👏👏😉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="75%">

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 07:50 UTC, merged